const div22=document.createElement("div");
div22.setAttribute("style", "width:120px; height:50px");
document.querySelector("body").appendChild(div22);
const image15=document.createElement("img");
image15.setAttribute("src","logo.png");
image15.setAttribute("style"," widht:50px; height:50px; margin-left:1000px; margin-top:0px; background-color:black");
div22.appendChild(image15);
const p12=document.createElement("p");
p12.setAttribute("style"," width:100px;margin-left:1070px; font-size:18px; margin-top:-45px");
p12.innerText="Techiee";
div22.appendChild(p12);
const p15=document.createElement("p");
p15.setAttribute("style"," width:100px;margin-left:1128px; color:orange;font-size:18px; margin-top:-38px");
p15.innerText="GY";
div22.appendChild(p15);
const p14=document.createElement("p");
p14.setAttribute("style"," width:100px;margin-left:1072px; font-size:10px; color:grey; margin-top:-15px");
p14.innerText="Entertained Learning";
div22.appendChild(p14);
const div1=document.createElement("div");
div1.setAttribute("style", "background-color:#4d5656; width:100%; height:200px; margin-top:10px");
document.querySelector("body").appendChild(div1);
const image=document.createElement("img");
image.setAttribute("src","log2.jpg");
image.setAttribute("style"," widht:150px; height:150px; margin-left:500px; margin-top:40px; border-radius:50%; border-style: dotted;  border: 200px dotted orange; border-width:5px; border-height:5px;");
div1.appendChild(image);
const btn=document.createElement("button");
btn.setAttribute("style","margin-top:-25px; margin-left:380px; background-color: orange; width:400px; height:70px; border:1px solid orange;")
div1.appendChild(btn);
const strong1=document.createElement("strong");
strong1.setAttribute("style","font-size:48px; margin-top:5px");
strong1.innerText="BRAIN DUDEY";
btn.appendChild(strong1);
const div2=document.createElement("div");
div2.setAttribute("style", "background-color: #f2f3f4; width:100%; height:35px");
document.querySelector("body").appendChild(div2);
const div3=document.createElement("div");
div3.setAttribute("style", "background-color: #4d5656; width:100%; height:35px");
document.querySelector("body").appendChild(div3);
const center1=document.createElement("center");
document.querySelector("body").appendChild(center1);
const h31=document.createElement("h3");
h31.setAttribute("style","color:#2E2E2E;");
h31.innerText="N.Damen A venue,chicago 99999 | 999-999-9999 | hello@kickresume.com | www.kickresume.com";
center1.appendChild(h31);
const hr1=document.createElement("hr");
hr1.setAttribute("style","color:#d5dbdb  ");
document.querySelector("body").appendChild(hr1);
const div16=document.createElement("div");
div16.setAttribute("style","border-left: 2px solid grey;height: 1020px;position: absolute;left: 50%;margin-left: -3px;top:410px");
document.querySelector("body").appendChild(div16);
const div4=document.createElement("div");
document.querySelector("body").appendChild(div4);
const image1=document.createElement("img");
image1.setAttribute("src","log4.png");
image1.setAttribute("style"," widht:50px; height:50px; margin-left:150px; border-radius:50%;border-style: dotted;  border: 2px dotted orange; border-width155px; border-height:15px");
div4.appendChild(image1);
const p1=document.createElement("p");
p1.setAttribute("style","margin-top:-40px; margin-left:220px; color: grey; font-size:32px");
p1.innerText="Profile";
div4.appendChild(p1);
const div5=document.createElement("div");
div5.setAttribute("style"," margin-top:-20px;margin-left:160px;");
div4.appendChild(div5);
const pre1=document.createElement("pre");
div5.appendChild(pre1);
const font1=document.createElement("font");
pre1.appendChild(font1);
font1.setAttribute("size","4");
font1.setAttribute("face","times new roman");
font1.innerText="Innovation optimized solution seeker.Excited to be \nat  the  deployment  phase  of  my  new career as a \nweb  developer . I  am   ambitions , adventurous  ,\nassiduous , animated, and an alliteration advocate.";

const div6=document.createElement("div");
document.querySelector("body").appendChild(div6);
const image2=document.createElement("img");
image2.setAttribute("src","log.png");
image2.setAttribute("style"," widht:50px; height:50px; margin-left:150px; border-radius:50%;border-style: dotted;  border: 2px dotted orange; border-width155px; border-height:15px");
div6.appendChild(image2);
const p2=document.createElement("p");
p2.setAttribute("style","margin-top:-40px; margin-left:220px; color: grey; font-size:32px");
p2.innerText="Skils";
div6.appendChild(p2);
const div7=document.createElement("div");
div7.setAttribute("style","margin-left:260px;margin-top:-30px; font-size:22px");
document.querySelector("body").appendChild(div7);
const strong2=document.createElement("strong");
strong2.innerText="Technical skils";
div7.appendChild(strong2);
const div8=document.createElement("div");
div8.setAttribute("style","width:250px");
document.querySelector("body").appendChild(div8);
const p3=document.createElement("p");
p3.setAttribute("style","font-size:16px; margin-left:150px");
p3.innerText="JavaScript\t\nCSS\t\nHTML\t\nReact\t\nRedux\t\nMongo\t\nDeployment";
div8.appendChild(p3);
const div9=document.createElement("div");
div8.appendChild(div9);
div9.setAttribute("style"," width:200px; margin-left:305px; margin-top:-145px;");
const input=document.createElement("input");
input.setAttribute("type","range");
input.setAttribute("value","80");
input.setAttribute("disabled","disabled");
const br=document.createElement("br");
input.appendChild(br);
const input1=document.createElement("input");
input1.setAttribute("type","range");
input1.setAttribute("value","80");
input1.setAttribute("disabled","disabled");
const br1=document.createElement("br");
input1.appendChild(br1);
const input2=document.createElement("input");
input2.setAttribute("type","range");
input2.setAttribute("value","50");
input2.setAttribute("disabled","disabled");
const br2=document.createElement("br");
input2.appendChild(br2);
const input3=document.createElement("input");
input3.setAttribute("type","range");
input3.setAttribute("value","50");
input3.setAttribute("disabled","disabled");
const br3=document.createElement("br");
input3.appendChild(br3);
const input4=document.createElement("input");
input4.setAttribute("type","range");
input4.setAttribute("value","80");
input4.setAttribute("disabled","disabled");
const br4=document.createElement("br");
input4.appendChild(br4);
const input5=document.createElement("input");
input5.setAttribute("type","range");
input5.setAttribute("value","80");
input5.setAttribute("disabled","disabled");
const br5=document.createElement("br");
input5.appendChild(br5);
const input6=document.createElement("input");
input6.setAttribute("type","range");
input6.setAttribute("value","100");
input6.setAttribute("disabled","disabled");
const br6=document.createElement("br");
input6.appendChild(br6);
div9.appendChild(input);
div9.appendChild(input1);
div9.appendChild(input2);
div9.appendChild(input3);
div9.appendChild(input4);
div9.appendChild(input5);
div9.appendChild(input6);

const div10=document.createElement("div");
div10.setAttribute("style","margin-left:260px;margin-top:30px; font-size:22px");
document.querySelector("body").appendChild(div10);
const strong3=document.createElement("strong");
strong3.innerText="Additional Skils";
div10.appendChild(strong3);
const div11=document.createElement("div");
div11.setAttribute("style","width:310px");
document.querySelector("body").appendChild(div11);
const p4=document.createElement("p");
p4.setAttribute("style","font-size:16px; margin-left:150px");
p4.innerText="Project Management\t\nRecruitment\t\nBusiness Development\t\nEditing\t\nFundraising";
div11.appendChild(p4);
const div12=document.createElement("div");
div11.appendChild(div12);
div12.setAttribute("style"," width:200px; margin-left:305px; margin-top:-110px;");
const input7=document.createElement("input");
input7.setAttribute("type","range");
input7.setAttribute("value","100");
input7.setAttribute("disabled","disabled");
div12.appendChild(input7);
const input8=document.createElement("input");
input8.setAttribute("type","range");
input8.setAttribute("value","80");
input8.setAttribute("disabled","disabled");
div12.appendChild(input8);
const input9=document.createElement("input");
input9.setAttribute("type","range");
input9.setAttribute("value","100");
input9.setAttribute("disabled","disabled");
div12.appendChild(input9);
const input10=document.createElement("input");
input10.setAttribute("type","range");
input10.setAttribute("value","80");
input10.setAttribute("disabled","disabled");
div12.appendChild(input10);
const input11=document.createElement("input");
input11.setAttribute("type","range");
input11.setAttribute("value","100");
input11.setAttribute("disabled","disabled");
div12.appendChild(input11);
const div14=document.createElement("div");
div14.setAttribute("style","margin-top:20px");
document.querySelector("body").appendChild(div14);
const image12=document.createElement("img");
image12.setAttribute("src","log5.png");
image12.setAttribute("style"," widht:50px; height:50px; margin-left:150px; border-radius:50%;border-style: dotted;  border: 2px dotted orange; border-width155px; border-height:15px");
div14.appendChild(image12);
const p5=document.createElement("p");
p5.setAttribute("style","margin-top:-40px; margin-left:220px; color: grey; font-size:32px");
p5.innerText="Work Experience";
div14.appendChild(p5);
const div15=document.createElement("div");
div15.setAttribute("style","margin-left:150px; margin-top:-15px");
document.querySelector("body").appendChild(div15);
const strong4=document.createElement("strong");
div15.appendChild(strong4);
strong4.innerText="Event Manager";
const h4=document.createElement("h4");
document.querySelector("body").appendChild(h4);
h4.setAttribute("style","font-size:18px; margin-left:389px; margin-top:-20px");
h4.innerText="03/2014 - 02/2017";
const p6=document.createElement("p");
document.querySelector("body").appendChild(p6);
p6.setAttribute("style","font-size:18px; margin-left:150px; margin-top:-20px");
p6.innerText="C3 presents,Washington dictsort";
const pre4=document.createElement("pre");
document.querySelector("body").appendChild(pre4);
const ul=document.createElement("ul");
pre4.appendChild(ul);
const li=document.createElement("li");
li.setAttribute("style","margin-left:150px; font-size:18px;width:400px; font-family:Times New Roman");
li.innerText="Lead and execute all phases of event planning\nand    production        spanning       committee\nrecruitment ,training ,vendor relationships and\non-site facilitation";
ul.appendChild(li);
const li1=document.createElement("li");
li1.setAttribute("style","margin-left:150px; margin-top:10px;font-size:18px;width:400px; font-family:Times New Roman");
li1.innerText="Brought  new   business  to  the    organization\nthrough relentless networking and stewardship\nwhich helped the company win the  bid for the\nState  Department  Summit on the Middle East\nand, the  companies largest civic event to  date,\nthe United State of Women";
ul.appendChild(li1);
const li2=document.createElement("li");
li2.setAttribute("style","margin-left:150px; margin-top:10px;font-size:18px;width:400px; font-family:Times New Roman");
li2.innerText="Exercise  fiscal  control  over  budget  creation\ntracking   and   reporting  .   Collaborate   with\nemployess   at   all  organizational   levels   to\nadvance cohesive operations.";
ul.appendChild(li2);
const div17=document.createElement("div");
div17.setAttribute("style","margin-top:-1029px");
document.querySelector("body").appendChild(div17);
const image13=document.createElement("img");
image13.setAttribute("src","log5.png");
image13.setAttribute("style"," widht:50px; height:50px; margin-left:700px; border-radius:50%;border-style: dotted;  border: 2px dotted orange; border-width155px; border-height:15px");
div17.appendChild(image13);
const p7=document.createElement("p");
p7.setAttribute("style","margin-top:-50px; margin-left:770px; color: grey; font-size:32px");
p7.innerText="Work Experience";
div17.appendChild(p7);
const div18=document.createElement("div");
div18.setAttribute("style","margin-left:700px; margin-top:-15px");
document.querySelector("body").appendChild(div18);
const strong5=document.createElement("strong");
div18.appendChild(strong5);
strong5.innerText="Community Relations\nManager";
const h41=document.createElement("h4");
document.querySelector("body").appendChild(h41);
h41.setAttribute("style","font-size:18px; margin-left:930px; margin-top:-35px");
h41.innerText=" 06/2011 - 01/2014";
const p8=document.createElement("p");
document.querySelector("body").appendChild(p8);
p8.setAttribute("style","font-size:18px; margin-left:700px; margin-top:10px");
p8.innerText="Gay & Lesbian Elder Housing, Los Angeles";

const pre5=document.createElement("pre");
document.querySelector("body").appendChild(pre5);
const ul1=document.createElement("ul");
pre5.appendChild(ul1);
const li4=document.createElement("li");
li4.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li4.innerText="Arranging   presentations    and   pitch  deck.";
ul1.appendChild(li4);
const li5=document.createElement("li");
li5.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li5.innerText="Designing   a   PR   plan  and    establishing\nimportant focus points.";
ul1.appendChild(li5);
const li6=document.createElement("li");
li6.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li6.innerText="Designing ,  creating  and   managing  content\nacross   multiple  communication    platforms. ";
ul1.appendChild(li6);
const li7=document.createElement("li");
li7.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li7.innerText="Building relationships with key media players.";
ul1.appendChild(li7);

const div19=document.createElement("div");
div19.setAttribute("style","margin-top:40px");
document.querySelector("body").appendChild(div19);
const image14=document.createElement("img");
image14.setAttribute("src","log6.png");
image14.setAttribute("style"," widht:50px; height:50px; margin-left:700px; border-radius:50%;border-style: dotted;  border: 2px dotted orange; border-width155px; border-height:15px");
div19.appendChild(image14);
const p9=document.createElement("p");
p9.setAttribute("style","margin-top:-50px; margin-left:780px; color: grey; font-size:32px");
p9.innerText="Education";
div19.appendChild(p9);
const div20=document.createElement("div");
div20.setAttribute("style","margin-left:700px; margin-top:-15px");
document.querySelector("body").appendChild(div20);
const strong6=document.createElement("strong");
div20.appendChild(strong6);
strong6.innerText="Engineering immersion\nProgram";
const h42=document.createElement("h4");
document.querySelector("body").appendChild(h42);
h42.setAttribute("style","font-size:18px; margin-left:930px; margin-top:-35px");
h42.innerText="11/2018 - 06/2018";
const p10=document.createElement("p");
document.querySelector("body").appendChild(p10);
p10.setAttribute("style","font-size:18px; margin-left:700px; margin-top:10px");
p10.innerText="Thinkful, Chicago,IL\n\nProject-focused intensive program with emphasis\non Mongo,Express,React, and JavaScript (MERN)\ntechnical stack.";
const pre6=document.createElement("pre");
document.querySelector("body").appendChild(pre6);
const ul2=document.createElement("ul");
pre6.appendChild(ul2);
const li8=document.createElement("li");
li8.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li8.innerText="Developed   a   full-stack   web   application,\n'RenewU' ,using React  that  allows users  to\nexplore various aspects of meditation.User's\nprogress is stored on  backend created using\nNode and MongoDB.";
ul2.appendChild(li8);
const li9=document.createElement("li");
li9.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li9.innerText="Developed  language Learning app, ' Foodie\nPhonetics'using spaced repetition and linked\nlist data structue.React  was  used to created\nthe  front  end  components  while  Node and\nMongo  were  used  to create  a backend that\nstores user data.";
ul2.appendChild(li9);
const li10=document.createElement("li");
li10.setAttribute("style","margin-left:700px; font-size:18px;width:400px; font-family:Times New Roman");
li10.innerText="Developed a  concierge app, 'pley',  for\nindividuals looking for curated  suggestions\nwhen visting a new place. React was  used to\ndevelop the frontend which includes real-time\nchat,drag and  drop and  variety of advanced\nfeatures. The  backend,  built  using   Node,\nExpress, and Mongo,takes advantage of   well-\ndeveloped RESTful API, Geospatial  searching,\nand user authentication with JWT.";
ul2.appendChild(li10);

const div21=document.createElement("div");
div21.setAttribute("style","margin-left:740px; margin-top:5px");
document.querySelector("body").appendChild(div21);
const strong7=document.createElement("strong");
div21.appendChild(strong7);
strong7.innerText="B.A,English";
const h45=document.createElement("h4");
document.querySelector("body").appendChild(h45);
h45.setAttribute("style","font-size:18px; margin-left:929px; margin-top:-20px");
h45.innerText="  09/2001-09/2006";
const p11=document.createElement("p");
document.querySelector("body").appendChild(p11);
p11.setAttribute("style","font-size:18px; margin-left:740px; margin-top:-20px");
p11.innerText="University of California,Los Angles";